### ISSUE TITLE
compilation on linux?

### ISSUE THREAD

**Issue by s1LenT0R** [seedee/SDHLT#5]
hello guys, i use the linux version of jack and would like to try this and compare it to Vluzacn's ZHLT v34 which i used before, can you add support for compilation with gcc like make files etc maybe?

**Comment by SmileYzn** [comment]
@sofachillax 

I want it too, there is a pull request here https://github.com/seedee/SDHLT/pull/2

Maybe @seedee  abandoned the repository?

**Comment by mconicx** [comment]
> Maybe seedee abandoned the repository?

 Seems like it. Pity...

**Comment by seedee** [comment]
> @sofachillax
> 
> I want it too, there is a pull request here #2
> 
> Maybe @seedee abandoned the repository?

Yeah, I did. Its now merged
