### ISSUE TITLE
CSG -worldextent not extending map limits

### ISSUE THREAD

**Issue by mconicx** [seedee/SDHLT#7]
I'm using J.A.C.K 1.1.3773 with SDHLT, and when I add the parameter "-worldextent 100000" for example, but I place a scientist for example outside the +-32768 bounds, the scientist follows me beyond the limit, but his model is rendered within the bounds.

**Comment by seedee** [comment]
The extent applies to world geometry only, entities are handled by the server. This would have happened with a default _delta.lst_ if players are `+/- 8192`, while entities are `+/- 4096`. Tt's not possible for any entity including brush ents `Entity n, Brush n: outside world` to go that far. In vanilla, _delta.lst_ is set at max `+/- 4096 units` from the origin. I recommend no more than `+/- 131072`, which is 262k in diameter.

Side note, there may also be an issue with Valve's implementation of sprites beyond `+/- 8192`.
